---
deployment:
  tasks:
    - export DEPLOYPATH=/home/glolbka/bank-app
    - /bin/cp -a . $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
    - if [ -d "/home/glolbka/public_html" ]; then /bin/cp -a dist/* /home/glolbka/public_html/ 2>/dev/null || true; fi
