import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';

export type LanguageCode = 'en' | 'de' | 'fr' | 'it' | 'es' | 'zh' | 'ar' | 'ru' | 'pt' | 'ja';

export interface LanguageOption {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'zh', name: 'Chinese', nativeName: '简体中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇦🇪', dir: 'rtl' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', dir: 'ltr' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation & General
    home: 'Home',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    login: 'Login',
    applyMembership: 'Apply for Membership',
    privateBanking: 'Private Banking',
    securityBadge: 'Swiss Banking Grade Security',
    heroTitle1: 'Banking Beyond Borders.',
    heroTitle2: 'Exclusivity Redefined.',
    heroSubtitle: 'Global Elite Bank is not for everyone. It is for those who demand excellence, expect privacy, and operate on a global scale. Membership is by application and approval only.',
    explorePrivileges: 'Explore Privileges',
    assetsUnderManagement: 'Assets Under Management',
    countriesServed: 'Countries Served',
    approvedMembers: 'Approved Members',
    uptimeReliability: 'Uptime & Vault Security',
    quickLinks: 'Quick Links',
    footerDescription: 'Global Elite Bank is a private financial institution serving an exclusive community of high-net-worth individuals and businesses. Membership is by application and approval only.',
    
    // Dashboard & Header
    dashboard: 'Dashboard',
    transactionHistory: 'Transaction History',
    cryptoFx: 'Crypto & FX',
    investorsWallet: 'Investors Wallet',
    virtualCards: 'Virtual Cards',
    loansGrants: 'Loans & Grants',
    analytics: 'Analytics',
    settings: 'Settings',
    adminPortal: 'Admin Portal',
    logout: 'Logout',
    totalBalance: 'Total Available Balance',
    accountNumber: 'Account Number',
    quickActions: 'Quick Actions',
    transferMoney: 'Transfer Money',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    recentTransactions: 'Recent Transactions',
    searchPlaceholder: 'Search assets, txns, or accounts...',
    segregatedVault: 'SEGREGATED VAULT SECURED',
    officialInstructions: 'Official Account Payment & Deposit Instructions',
    viewPaymentDetails: 'View Payment Details',
    selectLanguage: 'Select Language',
    currentLanguage: 'Language',
    
    // AI Chat
    aiChatTitle: 'Private Wealth Concierge',
    aiChatSubtitle: 'Powered by Gemini AI • 24/7 Swiss Discretion',
    aiChatPlaceholder: 'Ask about accounts, wires, crypto custody, or loans...',
    aiSend: 'Send',
    quickQuestions: 'Suggested Inquiries',
    q1: 'How do I apply for an account?',
    q2: 'What are international wire limits?',
    q3: 'Tell me about crypto vault custody',
    q4: 'Swiss privacy & asset protection',
    clearChat: 'Clear Conversation',
    onlineStatus: 'Online • 24/7 Instant Service',
    welcomeMessage: 'Welcome to Global Elite Bank. I am Aura, your dedicated 24/7 AI Private Wealth Concierge. How may I assist your private banking inquiries today?',
    typing: 'Aura is composing a response...',
    chatWithConcierge: 'AI Concierge',
  },
  de: {
    home: 'Startseite',
    about: 'Über uns',
    services: 'Dienstleistungen',
    contact: 'Kontakt',
    login: 'Anmelden',
    applyMembership: 'Mitgliedschaft beantragen',
    privateBanking: 'Privatbank',
    securityBadge: 'Schweizer Bankensicherheit',
    heroTitle1: 'Banking über Grenzen hinweg.',
    heroTitle2: 'Exklusivität neu definiert.',
    heroSubtitle: 'Global Elite Bank ist nicht für jedermann. Sie ist für jene bestimmt, die Exzellenz verlangen, Diskretion erwarten und im weltweiten Maßstab handeln. Mitgliedschaft nur auf Antrag.',
    explorePrivileges: 'Privilegien entdecken',
    assetsUnderManagement: 'Verwaltetes Vermögen',
    countriesServed: 'Betreute Länder',
    approvedMembers: 'Verifizierte Mitglieder',
    uptimeReliability: 'Verfügbarkeit & Tresorsicherheit',
    quickLinks: 'Schnellzugriff',
    footerDescription: 'Global Elite Bank ist ein privates Finanzinstitut für vermögende Privatkunden und Unternehmen. Aufnahme erfolgt streng nach Antragsprüfung.',
    
    dashboard: 'Übersicht',
    transactionHistory: 'Transaktionsverlauf',
    cryptoFx: 'Krypto & Devisen',
    investorsWallet: 'Investoren-Wallet',
    virtualCards: 'Virtuelle Karten',
    loansGrants: 'Kredite & Zuschüsse',
    analytics: 'Analysen',
    settings: 'Einstellungen',
    adminPortal: 'Admin-Portal',
    logout: 'Abmelden',
    totalBalance: 'Verfügbares Gesamtguthaben',
    accountNumber: 'Kontonummer',
    quickActions: 'Schnellaktionen',
    transferMoney: 'Geld überweisen',
    deposit: 'Einzahlen',
    withdraw: 'Auszahlen',
    recentTransactions: 'Letzte Transaktionen',
    searchPlaceholder: 'Assets, Überweisungen, Konten suchen...',
    segregatedVault: 'TRESORE FINMA-GESICHERT',
    officialInstructions: 'Offizielle Zahlungs- & Einzahlungsanweisungen',
    viewPaymentDetails: 'Zahlungsdetails ansehen',
    selectLanguage: 'Sprache wählen',
    currentLanguage: 'Sprache',
    
    aiChatTitle: 'Privater Vermögens-Concierge',
    aiChatSubtitle: 'Unterstützt von Gemini AI • 24/7 Schweizer Diskretion',
    aiChatPlaceholder: 'Fragen zu Konten, Überweisungen, Krypto oder Krediten...',
    aiSend: 'Senden',
    quickQuestions: 'Häufige Anfragen',
    q1: 'Wie beantrage ich ein Konto?',
    q2: 'Gibt es Überweisungslimits?',
    q3: 'Informationen zur Krypto-Verwahrung',
    q4: 'Schweizer Datenschutz & Vermögensschutz',
    clearChat: 'Verlauf leeren',
    onlineStatus: 'Online • 24/7 Sofortservice',
    welcomeMessage: 'Willkommen bei der Global Elite Bank. Ich bin Aura, Ihr persönlicher 24/7 AI Private Wealth Concierge. Wie kann ich Ihnen heute behilflich sein?',
    typing: 'Aura antwortet...',
    chatWithConcierge: 'AI Concierge',
  },
  fr: {
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    contact: 'Contact',
    login: 'Connexion',
    applyMembership: 'Demander l\'adhésion',
    privateBanking: 'Banque Privée',
    securityBadge: 'Sécurité Bancaire Suisse',
    heroTitle1: 'La banque au-delà des frontières.',
    heroTitle2: 'L\'exclusivité redéfinie.',
    heroSubtitle: 'Global Elite Bank n\'est pas pour tout le monde. Elle est dédiée à ceux qui exigent l\'excellence, la confidentialité absolue et opèrent à l\'échelle mondiale. Adhésion sur candidature uniquement.',
    explorePrivileges: 'Découvrir les privilèges',
    assetsUnderManagement: 'Actifs sous gestion',
    countriesServed: 'Pays desservis',
    approvedMembers: 'Membres agréés',
    uptimeReliability: 'Disponibilité & Coffres-forts',
    quickLinks: 'Liens rapides',
    footerDescription: 'Global Elite Bank est une institution financière privée servant une communauté exclusive d\'investisseurs et d\'entreprises.',
    
    dashboard: 'Tableau de bord',
    transactionHistory: 'Historique des transactions',
    cryptoFx: 'Crypto & FX',
    investorsWallet: 'Portefeuille Investisseurs',
    virtualCards: 'Cartes Virtuelles',
    loansGrants: 'Prêts & Subventions',
    analytics: 'Analytiques',
    settings: 'Paramètres',
    adminPortal: 'Portail Admin',
    logout: 'Déconnexion',
    totalBalance: 'Solde total disponible',
    accountNumber: 'Numéro de compte',
    quickActions: 'Actions rapides',
    transferMoney: 'Effectuer un virement',
    deposit: 'Déposer',
    withdraw: 'Retirer',
    recentTransactions: 'Transactions récentes',
    searchPlaceholder: 'Rechercher actifs, transactions...',
    segregatedVault: 'COFFRE-FORT SÉCURISÉ',
    officialInstructions: 'Instructions Officielles de Dépôt & Paiement',
    viewPaymentDetails: 'Voir les détails de paiement',
    selectLanguage: 'Choisir la langue',
    currentLanguage: 'Langue',
    
    aiChatTitle: 'Concierge Privé Dédié',
    aiChatSubtitle: 'Propulsé par Gemini AI • Discrétion Suisse 24/7',
    aiChatPlaceholder: 'Posez vos questions sur les comptes, virements, crypto...',
    aiSend: 'Envoyer',
    quickQuestions: 'Questions fréquentes',
    q1: 'Comment ouvrir un compte ?',
    q2: 'Quelles sont les limites de virement ?',
    q3: 'Sécurité et conservation crypto',
    q4: 'Confidentialité suisse & protection des avoirs',
    clearChat: 'Effacer la conversation',
    onlineStatus: 'En ligne • Service instantané 24/7',
    welcomeMessage: 'Bienvenue chez Global Elite Bank. Je suis Aura, votre concierge IA dédié à la gestion de fortune privée. En quoi puis-je vous être utile aujourd\'hui ?',
    typing: 'Aura rédige une réponse...',
    chatWithConcierge: 'Concierge IA',
  },
  it: {
    home: 'Home',
    about: 'Chi siamo',
    services: 'Servizi',
    contact: 'Contatti',
    login: 'Accedi',
    applyMembership: 'Richiedi adesione',
    privateBanking: 'Banca Privata',
    securityBadge: 'Sicurezza Bancaria Svizzera',
    heroTitle1: 'Banca oltre ogni confine.',
    heroTitle2: 'L\'esclusività ridefinita.',
    heroSubtitle: 'Global Elite Bank è riservata a chi esige eccellenza, assoluta discrezione e opera a livello internazionale. Accesso solo su approvazione.',
    explorePrivileges: 'Esplora i privilegi',
    assetsUnderManagement: 'Patrimonio gestito',
    countriesServed: 'Paesi serviti',
    approvedMembers: 'Membri approvati',
    uptimeReliability: 'Affidabilità e sicurezza caveau',
    quickLinks: 'Link rapidi',
    footerDescription: 'Global Elite Bank è un istituto finanziario privato al servizio di individui facoltosi e aziende di primo livello.',
    
    dashboard: 'Pannello di controllo',
    transactionHistory: 'Cronologia transazioni',
    cryptoFx: 'Crypto & FX',
    investorsWallet: 'Portafoglio Investitori',
    virtualCards: 'Carte Virtuali',
    loansGrants: 'Finanziamenti & Sovvenzioni',
    analytics: 'Analitica',
    settings: 'Impostazioni',
    adminPortal: 'Portale Admin',
    logout: 'Disconnetti',
    totalBalance: 'Saldo totale disponibile',
    accountNumber: 'Numero di conto',
    quickActions: 'Azioni rapide',
    transferMoney: 'Trasferisci fondi',
    deposit: 'Deposita',
    withdraw: 'Preleva',
    recentTransactions: 'Transazioni recenti',
    searchPlaceholder: 'Cerca asset, transazioni o conti...',
    segregatedVault: 'CAVEAU SEPARATO PROTETTO',
    officialInstructions: 'Istruzioni Ufficiali di Deposito e Pagamento',
    viewPaymentDetails: 'Visualizza dettagli di pagamento',
    selectLanguage: 'Seleziona lingua',
    currentLanguage: 'Lingua',
    
    aiChatTitle: 'Concierge Privato AI',
    aiChatSubtitle: 'Alimentato da Gemini AI • Discrezione Svizzera 24/7',
    aiChatPlaceholder: 'Chiedi informazioni su conti, bonifici, crypto o crediti...',
    aiSend: 'Invia',
    quickQuestions: 'Richieste suggerite',
    q1: 'Come richiedere un conto?',
    q2: 'Quali sono i massimali di bonifico?',
    q3: 'Custodia crypto e standard di sicurezza',
    q4: 'Protezione patrimoniale e segreto svizzero',
    clearChat: 'Cancella chat',
    onlineStatus: 'Online • Assistenza 24/7',
    welcomeMessage: 'Benvenuto in Global Elite Bank. Sono Aura, il tuo concierge AI per la gestione patrimoniale privata. Come posso assisterti oggi?',
    typing: 'Aura sta scrivendo...',
    chatWithConcierge: 'Concierge AI',
  },
  es: {
    home: 'Inicio',
    about: 'Nosotros',
    services: 'Servicios',
    contact: 'Contacto',
    login: 'Iniciar Sesión',
    applyMembership: 'Solicitar Membresía',
    privateBanking: 'Banca Privada',
    securityBadge: 'Seguridad Bancaria Suiza de Primer Nivel',
    heroTitle1: 'Banca sin fronteras.',
    heroTitle2: 'Exclusividad redefinida.',
    heroSubtitle: 'Global Elite Bank no es para todos. Es para quienes exigen excelencia, valoran la privacidad y operan globalmente. Membresía sujeta a aprobación.',
    explorePrivileges: 'Explorar Privilegios',
    assetsUnderManagement: 'Activos bajo administración',
    countriesServed: 'Países atendidos',
    approvedMembers: 'Miembros aprobados',
    uptimeReliability: 'Disponibilidad y seguridad de bóvedas',
    quickLinks: 'Enlaces rápidos',
    footerDescription: 'Global Elite Bank es una institución financiera privada que brinda servicios a una selecta comunidad de clientes de alto patrimonio.',
    
    dashboard: 'Panel Principal',
    transactionHistory: 'Historial de Transacciones',
    cryptoFx: 'Cripto & FX',
    investorsWallet: 'Billetera Inversores',
    virtualCards: 'Tarjetas Virtuales',
    loansGrants: 'Préstamos & Subvenciones',
    analytics: 'Analíticas',
    settings: 'Configuración',
    adminPortal: 'Portal Administrador',
    logout: 'Cerrar Sesión',
    totalBalance: 'Saldo total disponible',
    accountNumber: 'Número de cuenta',
    quickActions: 'Acciones Rápidas',
    transferMoney: 'Transferir Dinero',
    deposit: 'Depositar',
    withdraw: 'Retirar',
    recentTransactions: 'Transacciones Recientes',
    searchPlaceholder: 'Buscar activos, transacciones o cuentas...',
    segregatedVault: 'BÓVEDA SEGREGADA Y PROTEGIDA',
    officialInstructions: 'Instrucciones Oficiales de Depósito y Pago',
    viewPaymentDetails: 'Ver detalles de pago',
    selectLanguage: 'Seleccionar idioma',
    currentLanguage: 'Idioma',
    
    aiChatTitle: 'Conserje de Patrimonio Privado',
    aiChatSubtitle: 'Impulsado por Gemini AI • Discreción Suiza 24/7',
    aiChatPlaceholder: 'Pregunte sobre cuentas, transferencias, cripto o préstamos...',
    aiSend: 'Enviar',
    quickQuestions: 'Consultas habituales',
    q1: '¿Cómo solicitar una cuenta?',
    q2: '¿Cuáles son los límites de transferencia?',
    q3: 'Custodia institucional de criptomonedas',
    q4: 'Privacidad bancaria suiza y protección',
    clearChat: 'Limpiar conversación',
    onlineStatus: 'En línea • Asistencia 24/7',
    welcomeMessage: 'Bienvenido a Global Elite Bank. Soy Aura, su conserje privado de inteligencia artificial 24/7. ¿En qué puedo asistirle hoy?',
    typing: 'Aura está respondiendo...',
    chatWithConcierge: 'Conserje IA',
  },
  zh: {
    home: '首页',
    about: '关于我们',
    services: '专属服务',
    contact: '联系我们',
    login: '登录',
    applyMembership: '申请会员资格',
    privateBanking: '私人银行',
    securityBadge: '瑞士银行级最高安全标准',
    heroTitle1: '跨越国界的非凡金融。',
    heroTitle2: '重新定义至尊尊享。',
    heroSubtitle: '环球精英银行专为追求极致卓越、极度注重隐私并在全球范围拓展业务的高净值人士与企业设立。会员资格需审核批准。',
    explorePrivileges: '探索尊贵特权',
    assetsUnderManagement: '资产管理总额',
    countriesServed: '服务覆盖国家',
    approvedMembers: '尊贵认证会员',
    uptimeReliability: '系统可用性与金库安全',
    quickLinks: '快捷通道',
    footerDescription: '环球精英银行（Global Elite Bank）是一家服务全球高净值家族与跨国企业的专属私密金融机构。',
    
    dashboard: '资产总览',
    transactionHistory: '交易明细',
    cryptoFx: '加密货币与外汇',
    investorsWallet: '投资人钱包',
    virtualCards: '虚拟卡管理',
    loansGrants: '信贷与资助',
    analytics: '数据洞察',
    settings: '账户设置',
    adminPortal: '管理控制台',
    logout: '退出登录',
    totalBalance: '可用资产总额',
    accountNumber: '银行账号',
    quickActions: '快捷操作',
    transferMoney: '资金转账',
    deposit: '充值存款',
    withdraw: '提现提取',
    recentTransactions: '最新交易记录',
    searchPlaceholder: '搜索资产、明细或账户...',
    segregatedVault: '瑞士隔离金库安全保障',
    officialInstructions: '官方入金与汇款指南',
    viewPaymentDetails: '查看支付详细信息',
    selectLanguage: '选择语言',
    currentLanguage: '语言',
    
    aiChatTitle: '私人财富 AI 礼宾专员',
    aiChatSubtitle: '由 Gemini AI 驱动 • 瑞士级别 24/7 严密保密',
    aiChatPlaceholder: '咨询开户、跨境电汇、数字资产金库或大额信贷...',
    aiSend: '发送',
    quickQuestions: '精选咨询',
    q1: '如何申请专属账户？',
    q2: '国际电汇额度说明',
    q3: '加密资产瑞士冷钱包托管',
    q4: '瑞士隐私法案与资产保护',
    clearChat: '清空会话',
    onlineStatus: '在线 • 24/7 尊享服务',
    welcomeMessage: '尊贵的贵宾，欢迎访问环球精英银行。我是您的 24/7 私人财富 AI 礼宾顾问 Aura。请问今天如何为您提供专业协助？',
    typing: 'Aura 正在构思回复...',
    chatWithConcierge: 'AI 礼宾',
  },
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    services: 'الخدمات',
    contact: 'اتصل بنا',
    login: 'تسجيل الدخول',
    applyMembership: 'طلب العضوية',
    privateBanking: 'الخدمات المصرفية الخاصة',
    securityBadge: 'أعلى معايير الأمان المصرفي السويسري',
    heroTitle1: 'خدمات مصرفية تتجاوز الحدود.',
    heroTitle2: 'إعادة تعريف الحصرية والتميز.',
    heroSubtitle: 'بنك النخبة العالمي ليس للجميع؛ إنه مخصص لمن يطلبون التميز والسرية التامة على مستوى عالمي. العضوية تخضع للموافقة المسبقة.',
    explorePrivileges: 'استكشف المزايا الحصرية',
    assetsUnderManagement: 'الأصول المدارة',
    countriesServed: 'الدول المخدومة',
    approvedMembers: 'الأعضاء المعتمدون',
    uptimeReliability: 'أمان الخزائن والجاهزية',
    quickLinks: 'روابط سريعة',
    footerDescription: 'بنك النخبة العالمي هو مؤسسة مالية خاصة تقدم خدمات سرية حصرية لكبار الشخصيات والشركات الدولية.',
    
    dashboard: 'لوحة التحكم',
    transactionHistory: 'سجل المعاملات',
    cryptoFx: 'العملات الرقمية والفوركس',
    investorsWallet: 'محفظة المستثمرين',
    virtualCards: 'البطاقات الافتراضية',
    loansGrants: 'القروض والمنح',
    analytics: 'التحليلات',
    settings: 'الإعدادات',
    adminPortal: 'بوابة الإدارة',
    logout: 'تسجيل الخروج',
    totalBalance: 'إجمالي الرصيد المتاح',
    accountNumber: 'رقم الحساب',
    quickActions: 'إجراءات سريعة',
    transferMoney: 'تحويل أموال',
    deposit: 'إيداع',
    withdraw: 'سحب',
    recentTransactions: 'أحدث المعاملات',
    searchPlaceholder: 'بحث في الأصول أو المعاملات أو الحسابات...',
    segregatedVault: 'خزائن سويسرية منفصلة ومحمية',
    officialInstructions: 'تعليمات الإيداع والتحويل الرسمية',
    viewPaymentDetails: 'عرض تفاصيل الدفع',
    selectLanguage: 'اختر اللغة',
    currentLanguage: 'اللغة',
    
    aiChatTitle: 'مستشار الثروات الذكي الخاص',
    aiChatSubtitle: 'مدعوم بنظام Gemini الذكي • سرية سويسرية على مدار 24/7',
    aiChatPlaceholder: 'استفسر عن الحسابات، التحويلات، العملات الرقمية أو الائتمان...',
    aiSend: 'إرسال',
    quickQuestions: 'استفسارات مقترحة',
    q1: 'كيفية التقدم لفتح حساب خاص؟',
    q2: 'ما هي حدود التحويلات الدولية؟',
    q3: 'حفظ العملات الرقمية في خزائن باردة',
    q4: 'السرية المصرفية السويسرية وحماية الأصول',
    clearChat: 'مسح المحادثة',
    onlineStatus: 'متصل • خدمة فورية 24/7',
    welcomeMessage: 'أهلاً بكم في بنك النخبة العالمي. أنا أورا (Aura)، مستشاركم الرقمي الخاص لإدارة الثروات على مدار الساعة. كيف يمكنني خدمتكم اليوم؟',
    typing: 'أورا يكتب الرد الآن...',
    chatWithConcierge: 'المستشار الذكي',
  },
  ru: {
    home: 'Главная',
    about: 'О банке',
    services: 'Услуги',
    contact: 'Контакты',
    login: 'Вход',
    applyMembership: 'Подать заявку',
    privateBanking: 'Частный банкинг',
    securityBadge: 'Швейцарские стандарты банковской безопасности',
    heroTitle1: 'Банкинг без границ.',
    heroTitle2: 'Новый уровень эксклюзивности.',
    heroSubtitle: 'Global Elite Bank создан для тех, кто требует совершенства, ценит абсолютную конфиденциальность и мыслит глобально. Доступ только по приглашению и согласованию.',
    explorePrivileges: 'Изучить привилегии',
    assetsUnderManagement: 'Активы под управлением',
    countriesServed: 'Обслуживаемые страны',
    approvedMembers: 'Авторизованные клиенты',
    uptimeReliability: 'Надёжность и защита хранилищ',
    quickLinks: 'Быстрые ссылки',
    footerDescription: 'Global Elite Bank — частный швейцарский банк для состоятельных клиентов и корпораций.',
    
    dashboard: 'Обзор',
    transactionHistory: 'История транзакций',
    cryptoFx: 'Крипто & FX',
    investorsWallet: 'Кошелек инвестора',
    virtualCards: 'Виртуальные карты',
    loansGrants: 'Кредиты и гранты',
    analytics: 'Аналитика',
    settings: 'Настройки',
    adminPortal: 'Панель администратора',
    logout: 'Выйти',
    totalBalance: 'Общий доступный баланс',
    accountNumber: 'Номер счета',
    quickActions: 'Быстрые действия',
    transferMoney: 'Перевести средства',
    deposit: 'Пополнить',
    withdraw: 'Вывести',
    recentTransactions: 'Последние транзакции',
    searchPlaceholder: 'Поиск активов, переводов или счетов...',
    segregatedVault: 'СЕГРЕГИРОВАННЫЕ ХРАНИЛИЩА FINMA',
    officialInstructions: 'Официальные инструкции по пополнению счета',
    viewPaymentDetails: 'Посмотреть реквизиты',
    selectLanguage: 'Выбрать язык',
    currentLanguage: 'Язык',
    
    aiChatTitle: 'Персональный AI-Консьерж',
    aiChatSubtitle: 'На базе Gemini AI • Швейцарская конфиденциальность 24/7',
    aiChatPlaceholder: 'Вопросы о счетах, переводах SWIFT, криптохранилищах...',
    aiSend: 'Отправить',
    quickQuestions: 'Частые вопросы',
    q1: 'Как открыть премиальный счет?',
    q2: 'Лимиты на международные переводы',
    q3: 'Институциональное хранение криптовалют',
    q4: 'Швейцарская банковская тайна',
    clearChat: 'Очистить историю',
    onlineStatus: 'В сети • Поддержка 24/7',
    welcomeMessage: 'Добро пожаловать в Global Elite Bank. Я Aura — ваш персональный консьерж на базе искусственного интеллекта. Чем могу помочь вам сегодня?',
    typing: 'Aura печатает ответ...',
    chatWithConcierge: 'AI Консьерж',
  },
  pt: {
    home: 'Início',
    about: 'Sobre nós',
    services: 'Serviços',
    contact: 'Contato',
    login: 'Entrar',
    applyMembership: 'Solicitar Adesão',
    privateBanking: 'Private Banking',
    securityBadge: 'Segurança Padrão Suíço',
    heroTitle1: 'Banca sem fronteiras.',
    heroTitle2: 'Exclusividade redefinida.',
    heroSubtitle: 'O Global Elite Bank não é para todos. Destina-se àqueles que exigem excelência, priorizam privacidade e operam globalmente. Associação sujeita à aprovação.',
    explorePrivileges: 'Explorar Privilégios',
    assetsUnderManagement: 'Ativos sob Gestão',
    countriesServed: 'Países Atendidos',
    approvedMembers: 'Membros Aprovados',
    uptimeReliability: 'Disponibilidade e Segurança de Cofres',
    quickLinks: 'Links Rápidos',
    footerDescription: 'Global Elite Bank é uma instituição financeira privada voltada para famílias e corporações de alto patrimônio.',
    
    dashboard: 'Painel',
    transactionHistory: 'Histórico de Transações',
    cryptoFx: 'Cripto & FX',
    investorsWallet: 'Carteira de Investidores',
    virtualCards: 'Cartões Virtuais',
    loansGrants: 'Empréstimos e Subsídios',
    analytics: 'Análises',
    settings: 'Configurações',
    adminPortal: 'Portal do Administrador',
    logout: 'Sair',
    totalBalance: 'Saldo Total Disponível',
    accountNumber: 'Número da Conta',
    quickActions: 'Ações Rápidas',
    transferMoney: 'Transferir Dinheiro',
    deposit: 'Depositar',
    withdraw: 'Sacar',
    recentTransactions: 'Transações Recentes',
    searchPlaceholder: 'Buscar ativos, transações ou contas...',
    segregatedVault: 'COFRES SEGREGADOS E PROTEGIDOS',
    officialInstructions: 'Instruções Oficiais de Pagamento e Depósito',
    viewPaymentDetails: 'Ver Detalhes de Pagamento',
    selectLanguage: 'Selecionar Idioma',
    currentLanguage: 'Idioma',
    
    aiChatTitle: 'Concierge Privado de Patrimônio',
    aiChatSubtitle: 'Desenvolvido com Gemini AI • Discrição Suíça 24/7',
    aiChatPlaceholder: 'Dúvidas sobre contas, transferências, cripto ou linhas de crédito...',
    aiSend: 'Enviar',
    quickQuestions: 'Perguntas frequentes',
    q1: 'Como solicitar a abertura de conta?',
    q2: 'Quais são os limites para transferências?',
    q3: 'Custódia fria institucional de criptoativos',
    q4: 'Privacidade bancária suíça e proteção patrimonial',
    clearChat: 'Limpar Conversa',
    onlineStatus: 'Online • Atendimento 24/7',
    welcomeMessage: 'Bem-vindo ao Global Elite Bank. Sou Aura, seu concierge de inteligência artificial 24/7 para gestão patrimonial. Como posso ser útil hoje?',
    typing: 'Aura está digitando...',
    chatWithConcierge: 'Concierge IA',
  },
  ja: {
    home: 'ホーム',
    about: '当行について',
    services: 'サービス',
    contact: 'お問い合わせ',
    login: 'ログイン',
    applyMembership: '会員申請',
    privateBanking: 'プライベートバンキング',
    securityBadge: 'スイス銀行最高峰のセキュリティ基準',
    heroTitle1: '国境を越える資産運用。',
    heroTitle2: '最高峰のエクスクルーシブ。',
    heroSubtitle: 'グローバル・エリート・バンクはすべての方のための銀行ではありません。卓越性を求め、完全なる秘匿性を重視し、世界規模で活躍する方々のためのプライベートバンクです。',
    explorePrivileges: '特権・サービスを見る',
    assetsUnderManagement: '運用資産残高',
    countriesServed: 'サービス提供国',
    approvedMembers: '認定メンバー数',
    uptimeReliability: '稼働率および金庫保全体制',
    quickLinks: 'クイックリンク',
    footerDescription: 'グローバル・エリート・バンクは、富裕層個人およびグローバル企業のためのスイス基準プライベート金融機関です。',
    
    dashboard: 'ダッシュボード',
    transactionHistory: '取引履歴',
    cryptoFx: '暗号資産・為替',
    investorsWallet: '投資家ウォレット',
    virtualCards: 'バーチャルカード',
    loansGrants: '融資・助成金プログラム',
    analytics: '資産分析',
    settings: '設定',
    adminPortal: '管理ポータル',
    logout: 'ログアウト',
    totalBalance: '利用可能総残高',
    accountNumber: '口座番号',
    quickActions: 'クイックアクション',
    transferMoney: '資金送金',
    deposit: '入金',
    withdraw: '出金',
    recentTransactions: '最近の取引',
    searchPlaceholder: '資産、取引、口座を検索...',
    segregatedVault: 'スイス個別分離保管金庫で保護',
    officialInstructions: '公式入金・振込ご案内',
    viewPaymentDetails: '決済詳細を表示',
    selectLanguage: '言語を選択',
    currentLanguage: '言語',
    
    aiChatTitle: 'プライベートAIコンシェルジュ',
    aiChatSubtitle: 'Gemini AI 搭載 • 24時間スイス基準の厳格な機密性',
    aiChatPlaceholder: '口座開設、送金限度額、暗号資産保管についてご質問ください...',
    aiSend: '送信',
    quickQuestions: 'よくあるご質問',
    q1: 'プライベート口座の開設方法',
    q2: '国際送金の限度額について',
    q3: '暗号資産のコールドウォレット保管',
    q4: 'スイスの守秘義務と資産保全体制',
    clearChat: '履歴をクリア',
    onlineStatus: 'オンライン • 24時間体制',
    welcomeMessage: 'グローバル・エリート・バンクへようこそ。私はお客様専任の24時間プライベートAIコンシェルジュ「Aura（オーラ）」です。本日はどのようなご用件でしょうか？',
    typing: 'Aura が回答を作成中...',
    chatWithConcierge: 'AI コンシェルジュ',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  currentLanguageOption: LanguageOption;
  languages: LanguageOption[];
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    try {
      const saved = localStorage.getItem('geb_user_language') as LanguageCode;
      if (saved && SUPPORTED_LANGUAGES.some(l => l.code === saved)) {
        return saved;
      }
      // Check browser language
      const navLang = navigator.language?.split('-')[0]?.toLowerCase() as LanguageCode;
      if (navLang && SUPPORTED_LANGUAGES.some(l => l.code === navLang)) {
        return navLang;
      }
    } catch (_) {}
    return 'en';
  });

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code);
    try {
      localStorage.setItem('geb_user_language', code);
    } catch (_) {}
  };

  const currentLanguageOption = useMemo(() => {
    return SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = currentLanguageOption.dir;
  }, [language, currentLanguageOption.dir]);

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    // Fallback to English
    if (TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageOption,
        languages: SUPPORTED_LANGUAGES,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
